### ISSUE TITLE
could not find driver error

### ISSUE THREAD

**Issue by Adam1986** [f0rkz/Bootstrap-Nest-Administration-Tool#31]
Hello,

Just tried setting this up on a Ubuntu 18.04 container.

Installed Apache/PHP7.2 & MySQL and ensure PHP JSON module installed.

When trying to register a user, I simply get:

could not find driver

I've tried setting Apache to debug logging, as well as further PHP logging, but this doesn't give me any further information.

Can you help/advise?

**Comment by Adam1986** [comment]
Good morning,

Managed to resolve the above error by installing php7.2-mysql.

However, still cannot create a new user, my Apache error log shows:

`PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'user_location_lat' doesn't have a default value in /var/www/nest.domain.co.uk/includes/classes/registration.php:101\nStack trace:\n#0 /var/www/nest.domain.co.uk/includes/classes/registration.php(101): PDOStatement->execute(Array)\n#1 /var/www/nest.domain.co.uk/includes/classes/registration.php(29): Registration->registerNewUser()\n#2 /var/www/nest.domain.co.uk/web/index.php(34): Registration->__construct()\n#3 {main}\n  thrown in /var/www/nest.domain.co.uk/includes/classes/registration.php on line 101, referer: https://nest.domain.co.uk/index.php?page=register`

So I manually created a user with the longitute and latitude from Google Maps, and used a PHP password hash generator.  I could then logon to the site, when entering my Nest logon details I again get a 500 Internal Error, and the Apache log shows:

`PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /var/www/nest.domain.co.uk/includes/functions/encrypt_decrypt.php:6\nStack trace:\n#0 /var/www/nest.domain.co.uk/web/index.php(174): encrypt('Edgehill17@', 'ac6eaea2fa0196c...')\n#1 {main}\n  thrown in /var/www/nest.domain.co.uk/includes/functions/encrypt_decrypt.php on line 6, referer: https://nest.domain.co.uk/index.php?page=profile
`

Any help?

**Comment by Adam1986** [comment]
OK I installed php7.2-mbstring & php-curl and was then able to save the nest login information.  

I ran the script manually and it does appear to have done as it intended as I now have graphs building.  Is it normal for "Nest Control Panel" to just display the graphs? As I thought you should be able to control the Nest from here? Not getting any errors appearing in the Apache logs anymore however.

I am still unable to register via the site registration page however so that does appear to be an issue still.

Regards

**Comment by Adam1986** [comment]
Just wanted to give a little update on this.

The graphs are getting created, but noticing something odd when the thermostat is heating, the graph will randomly show the set-point at 9 degrees and then return to normal.  The Nest App indicates the same set-point throughout.

Taken a snip to indicate this more clearly:

<img width="838" alt="Capture" src="https://user-images.githubusercontent.com/9055956/54438976-c5424380-472f-11e9-9301-72b410fe87c8.PNG">

Don't know if this is something you have come across before?

**Comment by f0rkz** [comment]
Yeah, this means the thermostat is in "away" mode. For some reason the API gives that information when its in eco mode.

**Comment by Adam1986** [comment]
Sorry, I've only just sene that you've replied to this.

So am I correct in understanding that when the setpoint is set to 18.5 degrees, because this is classed as an eco temperature, the API responds as though the device is set to "away/eco" mode?

Because we do not use "Away" Mode on our Nest whatsoever.
